# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08760f40888559a56a06442ec01faccde3be9e696222c80773bdd427beb509b4e4ddf3e4c1f476f0af90b6f533a54000e1c813e3f47e0954485ba615be43d1ce

test:
  secret_key_base: 168a6c3e5b85f5ae3892bbe457424d3c4ac3ed5f9782529904da708f9dddfc83fb029356b61ab3f1bde20e9fc2990114f552b1333ac3a7d7c127b7aded393a31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
